# Generated by Django 4.1.7 on 2023-03-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id_col', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'colonne',
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('descr', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tache',
            },
        ),
        migrations.CreateModel(
            name='Associer',
            fields=[
                ('id_associer', models.AutoField(primary_key=True, serialize=False)),
                ('id_col', models.ForeignKey(blank=True, db_column='id_col', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.colonne')),
                ('id_task', models.ForeignKey(blank=True, db_column='tache', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tache')),
            ],
            options={
                'db_table': 'associer',
                'unique_together': {('id_col', 'id_task')},
            },
        ),
    ]
