# Generated by Django 4.1.7 on 2023-03-28 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associer',
            name='id_task',
            field=models.ForeignKey(blank=True, db_column='id_task', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tache'),
        ),
    ]
