# Generated by Django 4.1.7 on 2023-03-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_associer_id_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonne',
            name='pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='id_col',
            field=models.ForeignKey(blank=True, db_column='id_col', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.colonne'),
        ),
        migrations.AddField(
            model_name='tache',
            name='pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Associer',
        ),
    ]
